name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  ci:
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: server

      - name: Test
        run: go test ./internal/...
        working-directory: server

      - name: Build
        run: go build ./...
        working-directory: server

  cd:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Build release binary
        run: go build -o build/app
        working-directory: server

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: server/build/ 
