name: Static Analysis (golangci-lint)

on:
  pull_request:
    paths:
      - 'server/**.go'
      - 'server/go.mod'
      - 'server/go.sum'
  push:
    branches: [ main ]
    paths:
      - 'server/**.go'
      - 'server/go.mod'
      - 'server/go.sum'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59

      - name: Run golangci-lint
        run: golangci-lint run ./server/... --timeout=5m
